/* Copyright (c) 2014 by Jean-Marc.Viglino [at]ign.fr
* Dual-licensed under the CeCILL-B Licence (http://www.cecill.info/)
* and the Beerware license (http://en.wikipedia.org/wiki/Beerware), 
*
* Font definiton to use with fontsymbols
*/

import ol_style_FontSymbol from './FontSymbol'

ol_style_FontSymbol.addDefs ({
  "font":"fontmaki",
  "name":"Maki",
  "copyright":"CC0 - MapBox - https://www.mapbox.com/maki/",
  "prefix":"maki"
},
{	"maki-bicycle": {"font":"fontmaki","code":59392,"name":"bicycle","search":"bicycle"},
  "maki-building": {"font":"fontmaki","code":59393,"name":"building","search":"building"},
  "maki-bus": {"font":"fontmaki","code":59394,"name":"bus","search":"bus"},
  "maki-cafe": {"font":"fontmaki","code":59395,"name":"cafe","search":"cafe"},
  "maki-camera": {"font":"fontmaki","code":59396,"name":"camera","search":"camera"},
  "maki-campsite": {"font":"fontmaki","code":59397,"name":"campsite","search":"campsite"},
  "maki-car": {"font":"fontmaki","code":59398,"name":"car","search":"car"},
  "maki-cemetery": {"font":"fontmaki","code":59399,"name":"cemetery","search":"cemetery"},
  "maki-chemist": {"font":"fontmaki","code":59400,"name":"chemist","search":"chemist"},
  "maki-cinema": {"font":"fontmaki","code":59401,"name":"cinema","search":"cinema"},
  "maki-circle": {"font":"fontmaki","code":59402,"name":"circle","search":"circle"},
  "maki-circle_stroked": {"font":"fontmaki","code":59403,"name":"circle_stroked","search":"circle_stroked"},
  "maki-city": {"font":"fontmaki","code":59404,"name":"city","search":"city"},
  "maki-clothing_store": {"font":"fontmaki","code":59405,"name":"clothing_store","search":"clothing_store"},
  "maki-college": {"font":"fontmaki","code":59406,"name":"college","search":"college"},
  "maki-commercial": {"font":"fontmaki","code":59407,"name":"commercial","search":"commercial"},
  "maki-cricket": {"font":"fontmaki","code":59408,"name":"cricket","search":"cricket"},
  "maki-cross": {"font":"fontmaki","code":59409,"name":"cross","search":"cross"},
  "maki-dam": {"font":"fontmaki","code":59410,"name":"dam","search":"dam"},
  "maki-danger": {"font":"fontmaki","code":59411,"name":"danger","search":"danger"},
  "maki-dentist": {"font":"fontmaki","code":59412,"name":"dentist","search":"dentist"},
  "maki-disability": {"font":"fontmaki","code":59413,"name":"disability","search":"disability"},
  "maki-dog_park": {"font":"fontmaki","code":59414,"name":"dog_park","search":"dog_park"},
  "maki-embassy": {"font":"fontmaki","code":59415,"name":"embassy","search":"embassy"},
  "maki-emergency_telephone": {"font":"fontmaki","code":59416,"name":"emergency_telephone","search":"emergency_telephone"},
  "maki-entrance": {"font":"fontmaki","code":59417,"name":"entrance","search":"entrance"},
  "maki-farm": {"font":"fontmaki","code":59418,"name":"farm","search":"farm"},
  "maki-fast_food": {"font":"fontmaki","code":59419,"name":"fast_food","search":"fast_food"},
  "maki-ferry": {"font":"fontmaki","code":59420,"name":"ferry","search":"ferry"},
  "maki-fire_station": {"font":"fontmaki","code":59421,"name":"fire_station","search":"fire_station"},
  "maki-fuel": {"font":"fontmaki","code":59422,"name":"fuel","search":"fuel"},
  "maki-garden": {"font":"fontmaki","code":59423,"name":"garden","search":"garden"},
  "maki-gift": {"font":"fontmaki","code":59424,"name":"gift","search":"gift"},
  "maki-golf": {"font":"fontmaki","code":59425,"name":"golf","search":"golf"},
  "maki-grocery": {"font":"fontmaki","code":59426,"name":"grocery","search":"grocery"},
  "maki-hairdresser": {"font":"fontmaki","code":59427,"name":"hairdresser","search":"hairdresser"},
  "maki-harbor": {"font":"fontmaki","code":59428,"name":"harbor","search":"harbor"},
  "maki-heart": {"font":"fontmaki","code":59429,"name":"heart","search":"heart"},
  "maki-heliport": {"font":"fontmaki","code":59430,"name":"heliport","search":"heliport"},
  "maki-hospital": {"font":"fontmaki","code":59431,"name":"hospital","search":"hospital"},
  "maki-ice_cream": {"font":"fontmaki","code":59432,"name":"ice_cream","search":"ice_cream"},
  "maki-industrial": {"font":"fontmaki","code":59433,"name":"industrial","search":"industrial"},
  "maki-land_use": {"font":"fontmaki","code":59434,"name":"land_use","search":"land_use"},
  "maki-laundry": {"font":"fontmaki","code":59435,"name":"laundry","search":"laundry"},
  "maki-library": {"font":"fontmaki","code":59436,"name":"library","search":"library"},
  "maki-lighthouse": {"font":"fontmaki","code":59437,"name":"lighthouse","search":"lighthouse"},
  "maki-lodging": {"font":"fontmaki","code":59438,"name":"lodging","search":"lodging"},
  "maki-logging": {"font":"fontmaki","code":59439,"name":"logging","search":"logging"},
  "maki-london_underground": {"font":"fontmaki","code":59440,"name":"london_underground","search":"london_underground"},
  "maki-marker": {"font":"fontmaki","code":59441,"name":"marker","search":"marker"},
  "maki-minefield": {"font":"fontmaki","code":59442,"name":"minefield","search":"minefield"},
  "maki-marker_stroked": {"font":"fontmaki","code":59443,"name":"marker_stroked","search":"marker_stroked"},
  "maki-mobilephone": {"font":"fontmaki","code":59444,"name":"mobilephone","search":"mobilephone"},
  "maki-monument": {"font":"fontmaki","code":59445,"name":"monument","search":"monument"},
  "maki-museum": {"font":"fontmaki","code":59446,"name":"museum","search":"museum"},
  "maki-music": {"font":"fontmaki","code":59447,"name":"music","search":"music"},
  "maki-oil_well": {"font":"fontmaki","code":59448,"name":"oil_well","search":"oil_well"},
  "maki-park": {"font":"fontmaki","code":59449,"name":"park","search":"park"},
  "maki-park2": {"font":"fontmaki","code":59450,"name":"park2","search":"park2"},
  "maki-parking": {"font":"fontmaki","code":59451,"name":"parking","search":"parking"},
  "maki-parking_garage": {"font":"fontmaki","code":59452,"name":"parking_garage","search":"parking_garage"},
  "maki-pharmacy": {"font":"fontmaki","code":59453,"name":"pharmacy","search":"pharmacy"},
  "maki-pitch": {"font":"fontmaki","code":59454,"name":"pitch","search":"pitch"},
  "maki-playground": {"font":"fontmaki","code":59455,"name":"playground","search":"playground"},
  "maki-police": {"font":"fontmaki","code":59456,"name":"police","search":"police"},
  "maki-polling_place": {"font":"fontmaki","code":59457,"name":"polling_place","search":"polling_place"},
  "maki-post": {"font":"fontmaki","code":59458,"name":"post","search":"post"},
  "maki-prison": {"font":"fontmaki","code":59459,"name":"prison","search":"prison"},
  "maki-rail": {"font":"fontmaki","code":59460,"name":"rail","search":"rail"},
  "maki-rail_above": {"font":"fontmaki","code":59461,"name":"rail_above","search":"rail_above"},
  "maki-rail_light": {"font":"fontmaki","code":59462,"name":"rail_light","search":"rail_light"},
  "maki-rail_metro": {"font":"fontmaki","code":59463,"name":"rail_metro","search":"rail_metro"},
  "maki-rail_underground": {"font":"fontmaki","code":59464,"name":"rail_underground","search":"rail_underground"},
  "maki-religious-christian": {"font":"fontmaki","code":59465,"theme":"religious","name":"christian","search":"religious,christian"},
  "maki-religious-jewish": {"font":"fontmaki","code":59466,"theme":"religious","name":"jewish","search":"religious,jewish"},
  "maki-religious-muslim": {"font":"fontmaki","code":59467,"theme":"religious","name":"muslim","search":"religious,muslim"},
  "maki-religious-place_of_worship": {"font":"fontmaki","code":59468,"theme":"religious","name":"place_of_worship","search":"religious,place_of_worship"},
  "maki-restaurant": {"font":"fontmaki","code":59469,"name":"restaurant","search":"restaurant"},
  "maki-roadblock": {"font":"fontmaki","code":59470,"name":"roadblock","search":"roadblock"},
  "maki-rocket": {"font":"fontmaki","code":59471,"name":"rocket","search":"rocket"},
  "maki-school": {"font":"fontmaki","code":59472,"name":"school","search":"school"},
  "maki-scooter": {"font":"fontmaki","code":59473,"name":"scooter","search":"scooter"},
  "maki-shop": {"font":"fontmaki","code":59474,"name":"shop","search":"shop"},
  "maki-skiing": {"font":"fontmaki","code":59475,"name":"skiing","search":"skiing"},
  "maki-slaughterhouse": {"font":"fontmaki","code":59476,"name":"slaughterhouse","search":"slaughterhouse"},
  "maki-soccer": {"font":"fontmaki","code":59477,"name":"soccer","search":"soccer"},
  "maki-square": {"font":"fontmaki","code":59478,"name":"square","search":"square"},
  "maki-square_stroked": {"font":"fontmaki","code":59479,"name":"square_stroked","search":"square_stroked"},
  "maki-star": {"font":"fontmaki","code":59480,"name":"star","search":"star"},
  "maki-star_stroked": {"font":"fontmaki","code":59481,"name":"star_stroked","search":"star_stroked"},
  "maki-suitcase": {"font":"fontmaki","code":59482,"name":"suitcase","search":"suitcase"},
  "maki-swimming": {"font":"fontmaki","code":59483,"name":"swimming","search":"swimming"},
  "maki-telephone": {"font":"fontmaki","code":59484,"name":"telephone","search":"telephone"},
  "maki-tennis": {"font":"fontmaki","code":59485,"name":"tennis","search":"tennis"},
  "maki-theatre": {"font":"fontmaki","code":59486,"name":"theatre","search":"theatre"},
  "maki-toilets": {"font":"fontmaki","code":59487,"name":"toilets","search":"toilets"},
  "maki-town": {"font":"fontmaki","code":59488,"name":"town","search":"town"},
  "maki-town_hall": {"font":"fontmaki","code":59489,"name":"town_hall","search":"town_hall"},
  "maki-triangle": {"font":"fontmaki","code":59490,"name":"triangle","search":"triangle"},
  "maki-triangle_stroked": {"font":"fontmaki","code":59491,"name":"triangle_stroked","search":"triangle_stroked"},
  "maki-village": {"font":"fontmaki","code":59492,"name":"village","search":"village"},
  "maki-warehouse": {"font":"fontmaki","code":59493,"name":"warehouse","search":"warehouse"},
  "maki-waste_basket": {"font":"fontmaki","code":59494,"name":"waste_basket","search":"waste_basket"},
  "maki-water": {"font":"fontmaki","code":59495,"name":"water","search":"water"},
  "maki-wetland": {"font":"fontmaki","code":59496,"name":"wetland","search":"wetland"},
  "maki-zoo": {"font":"fontmaki","code":59497,"name":"zoo","search":"zoo"},
  "maki-aerialway": {"font":"fontmaki","code":59498,"name":"aerialway","search":"aerialway"},
  "maki-airfield": {"font":"fontmaki","code":59499,"name":"airfield","search":"airfield"},
  "maki-airport": {"font":"fontmaki","code":59500,"name":"airport","search":"airport"},
  "maki-alcohol_shop": {"font":"fontmaki","code":59501,"name":"alcohol_shop","search":"alcohol_shop"},
  "maki-america_football": {"font":"fontmaki","code":59502,"name":"america_football","search":"america_football"},
  "maki-art_gallery": {"font":"fontmaki","code":59503,"name":"art_gallery","search":"art_gallery"},
  "maki-bakery": {"font":"fontmaki","code":59504,"name":"bakery","search":"bakery"},
  "maki-bank": {"font":"fontmaki","code":59505,"name":"bank","search":"bank"},
  "maki-bar": {"font":"fontmaki","code":59506,"name":"bar","search":"bar"},
  "maki-baseball": {"font":"fontmaki","code":59507,"name":"baseball","search":"baseball"},
  "maki-basketball": {"font":"fontmaki","code":59508,"name":"basketball","search":"basketball"},
  "maki-beer": {"font":"fontmaki","code":59509,"name":"beer","search":"beer"},
});

export default ol_style_FontSymbol